# Generated by Django 5.2.7 on 2025-11-02 23:18

import django.contrib.postgres.fields
import django.db.models.deletion
import src.monet.models.audit_log
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_by_id", models.IntegerField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADDITION", "ADDITION"),
                            ("CHANGE", "CHANGE"),
                            ("DELETION", "DELETION"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=50)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "STUDENT"),
                            ("TEST", "TEST"),
                            ("QUESTION", "QUESTION"),
                            ("ANSWER", "ANSWER"),
                            ("FORM_STUDENT_QUESTION", "FORM_STUDENT_QUESTION"),
                            ("STUDENT_ANSWER_CHOICE", "STUDENT_ANSWER_CHOICE"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("obj_repr", models.CharField(max_length=100)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=src.monet.models.audit_log.metadata_default,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("API", "API"),
                            ("CMD_COMMAND", "CMD_COMMAND"),
                            ("ADMIN", "ADMIN"),
                        ],
                        db_index=True,
                        default="ADMIN",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_log",
            },
        ),
        migrations.CreateModel(
            name="FormStudentTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("correct_answers", models.SmallIntegerField(default=0)),
                ("wrong_answers", models.SmallIntegerField(default=0)),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "is_closed",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "db_table": "form_student_test",
            },
        ),
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("QUESTION_SINGLE", "QUESTION_SINGLE"),
                            ("QUESTION_MULTIPLE", "QUESTION_MULTIPLE"),
                        ],
                        db_index=True,
                        default="QUESTION_SINGLE",
                        max_length=50,
                    ),
                ),
                ("created_by_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_by_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": "test",
            },
        ),
        migrations.CreateModel(
            name="MultipleQuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "correct_answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="multiple_set",
                        to="monet.questionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "multiple_question",
            },
        ),
        migrations.CreateModel(
            name="AnswerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct_answer", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_set",
                        to="monet.questionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "nro_carnet",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="StudentAnswerChoiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monet.answermodel",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_answer_set",
                        to="monet.formstudenttestmodel",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monet.questionmodel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monet.studentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "student_answer_choice",
            },
        ),
        migrations.AddField(
            model_name="formstudenttestmodel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monet.studentmodel",
            ),
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_set",
                to="monet.testmodel",
            ),
        ),
        migrations.AddField(
            model_name="formstudenttestmodel",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monet.testmodel",
            ),
        ),
        migrations.CreateModel(
            name="TestSettingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("total_questions", models.SmallIntegerField(default=0)),
                (
                    "approval_percent",
                    models.CharField(
                        choices=[
                            ("PERCENT_50", "PERCENT_50"),
                            ("PERCENT_60", "PERCENT_60"),
                            ("PERCENT_70", "PERCENT_70"),
                            ("PERCENT_80", "PERCENT_80"),
                            ("PERCENT_90", "PERCENT_90"),
                            ("PERCENT_100", "PERCENT_100"),
                        ],
                        db_index=True,
                        default="PERCENT_50",
                        max_length=30,
                    ),
                ),
                ("has_retry", models.BooleanField(default=False)),
                ("retry_limit", models.IntegerField(default=0)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="monet.testmodel",
                    ),
                ),
            ],
            options={
                "db_table": "test_settings",
            },
        ),
        migrations.CreateModel(
            name="SingleQuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "correct_answer",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simple_set",
                        to="monet.questionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "single_question",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("question",),
                        name="unique_active_simple_question_per_question",
                    )
                ],
            },
        ),
    ]
